################################################################################
# Automatically-generated file. Do not edit!
# Toolchain: GNU Tools for STM32 (12.3.rel1)
################################################################################

ELF_SRCS := 
OBJ_SRCS := 
S_SRCS := 
C_SRCS := 
S_UPPER_SRCS := 
O_SRCS := 
CYCLO_FILES := 
OBJCOPY_HEX := 
SIZE_OUTPUT := 
OBJDUMP_LIST := 
SU_FILES := 
EXECUTABLES := 
OBJS := 
MAP_FILES := 
S_DEPS := 
S_UPPER_DEPS := 
C_DEPS := 
OBJCOPY_BIN := 

# Every subdirectory with source files must be described here
SUBDIRS := \
Core/Src \
Core/Startup \
Drivers/STM32F4xx_HAL_Driver/Src \
Hardware/DISP \
Hardware/TOUCH \
Midware/FatFS \
Midware/FreeRTOS \
Midware/FreeRTOS/portable \
Midware/LVGL/custom \
Midware/LVGL/generated \
Midware/LVGL/generated/guider_fonts \
Midware/LVGL/port \
Midware/LVGL/src/core \
Midware/LVGL/src/draw/arm2d \
Midware/LVGL/src/draw \
Midware/LVGL/src/draw/nxp/pxp \
Midware/LVGL/src/draw/nxp/vglite \
Midware/LVGL/src/draw/renesas \
Midware/LVGL/src/draw/sdl \
Midware/LVGL/src/draw/stm32_dma2d \
Midware/LVGL/src/draw/sw \
Midware/LVGL/src/draw/swm341_dma2d \
Midware/LVGL/src/extra/layouts/flex \
Midware/LVGL/src/extra/layouts/grid \
Midware/LVGL/src/extra/libs/barcode \
Midware/LVGL/src/extra/libs/bmp \
Midware/LVGL/src/extra/libs/ffmpeg \
Midware/LVGL/src/extra/libs/freetype \
Midware/LVGL/src/extra/libs/fsdrv \
Midware/LVGL/src/extra/libs/gif \
Midware/LVGL/src/extra/libs/png \
Midware/LVGL/src/extra/libs/qrcode \
Midware/LVGL/src/extra/libs/rlottie \
Midware/LVGL/src/extra/libs/sjpg \
Midware/LVGL/src/extra \
Midware/LVGL/src/extra/others/fragment \
Midware/LVGL/src/extra/others/gridnav \
Midware/LVGL/src/extra/others/ime \
Midware/LVGL/src/extra/others/imgfont \
Midware/LVGL/src/extra/others/monkey \
Midware/LVGL/src/extra/others/msg \
Midware/LVGL/src/extra/others/snapshot \
Midware/LVGL/src/extra/themes/basic \
Midware/LVGL/src/extra/themes/default \
Midware/LVGL/src/extra/themes/mono \
Midware/LVGL/src/extra/widgets/analogclock \
Midware/LVGL/src/extra/widgets/animimg \
Midware/LVGL/src/extra/widgets/calendar \
Midware/LVGL/src/extra/widgets/carousel \
Midware/LVGL/src/extra/widgets/chart \
Midware/LVGL/src/extra/widgets/colorwheel \
Midware/LVGL/src/extra/widgets/dclock \
Midware/LVGL/src/extra/widgets/imgbtn \
Midware/LVGL/src/extra/widgets/keyboard \
Midware/LVGL/src/extra/widgets/led \
Midware/LVGL/src/extra/widgets/list \
Midware/LVGL/src/extra/widgets/menu \
Midware/LVGL/src/extra/widgets/meter \
Midware/LVGL/src/extra/widgets/msgbox \
Midware/LVGL/src/extra/widgets/radiobtn \
Midware/LVGL/src/extra/widgets/span \
Midware/LVGL/src/extra/widgets/spinbox \
Midware/LVGL/src/extra/widgets/spinner \
Midware/LVGL/src/extra/widgets/tabview \
Midware/LVGL/src/extra/widgets/textprogress \
Midware/LVGL/src/extra/widgets/tileview \
Midware/LVGL/src/extra/widgets/win \
Midware/LVGL/src/font \
Midware/LVGL/src/hal \
Midware/LVGL/src/misc \
Midware/LVGL/src/widgets \
Midware/TinyUSB/hw/bsp \
Midware/TinyUSB/hw/bsp/stm32f4 \
Midware/TinyUSB/src/class/audio \
Midware/TinyUSB/src/class/bth \
Midware/TinyUSB/src/class/cdc \
Midware/TinyUSB/src/class/dfu \
Midware/TinyUSB/src/class/hid \
Midware/TinyUSB/src/class/midi \
Midware/TinyUSB/src/class/msc \
Midware/TinyUSB/src/class/net \
Midware/TinyUSB/src/class/usbtmc \
Midware/TinyUSB/src/class/vendor \
Midware/TinyUSB/src/class/video \
Midware/TinyUSB/src/common \
Midware/TinyUSB/src/device \
Midware/TinyUSB/src/host \
Midware/TinyUSB/src/portable/synopsys/dwc2 \
Midware/TinyUSB/src \
Midware/TinyUSB/src/typec \
Midware/TinyUSB \

